version: '3.9'
services:
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    container_name: changzhoutest_backend
    image: changzhoutest:greaterwms
    restart: always
    volumes:
      - ./:/ChangZhou/:rw # 将当前目录挂载到容器下
      - ./wait-for-mysql.sh:/wait-for-mysql.sh
    ports:
      - '8007:8007'
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - changzhougreaterwmstest-mysql
    command:
      - /bin/bash
      - -c
      - |
        bash backend_start.sh
    networks:
      network:
        ipv4_address: 172.14.0.16

  changzhougreaterwmstest-mysql:
    platform: linux/amd64
    image: mysql:8.0
    container_name: changzhougreaterwmstest-mysql
    privileged: true # 使用该参数，使容器内的root拥有真正的root权限
    restart: always
    ports:
       - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "GreaterWMS@@20210816"
      MYSQL_DATABASE: "greaterwms"
      TZ: Asia/Shanghai
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
      --socket=/var/run/mysqld/mysqld.sock
    volumes:
      - "./docker/mysql/data:/var/lib/mysql/data/"
      - "./docker/mysql/conf.d:/etc/mysql/conf.d"
      - "./docker/mysql/logs:/logs"
    networks:
      network:
        ipv4_address: 172.14.0.13

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '172.14.0.0/16'
