version: '3.9'
networks:
  basic:
services:
  front:
    build:
      context: ./
      dockerfile: ./docker/front/Dockerfile
    container_name: changzhou_front
    image: changzhou:greaterwmsfront
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/erp/frontend:rw
      - ./web_start.sh:/GreaterWMS/templates/web_start.sh
    command:
      - /bin/bash
      - -c
      #- "yarn install --force"
      - |
        bash /erp/frontend/web_start.sh
    networks:
      - basic
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    container_name: changzhou_backend
    image: changzhou:greaterwms
    restart: always
    volumes:
      - ./:/GreaterWMS/:rw #将前目录挂载到容器下
      - ./supervisord.conf:/etc/supervisor/supervisord.conf
    ports:
      - '8008:8008'
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - front
    command:
      - /bin/bash
      - -c
      - |
        bash backend_start.sh
    networks:
      - basic
#  dvadmin-redis:
#    image: redis:6.0.6
#    container_name: dvadmin-redis
#    privileged: true
#    ports:
#      - 6379:6379
#    command: redis-server /etc/redis/redis.conf --appendonly yes
#    environment:
#      TZ: Asia/Shanghai
#    volumes:
#      - ./docker/redis/data:/data
#      - ./docker/redis/conf/redis.conf:/etc/redis/redis.conf
#    restart: always
#    networks:
#      - basic
#    networks:
#      - basic
#   nginx:
#     image: nginx:1.19.1
#     container_name: greaterwms_nginx
#     restart: always
#     privileged: true
#     environment:
#       - TZ=Asia/Shanghai
#     ports:
#       - 80:80
#       #- 443:443
#     volumes:
#       - /etc/localtime:/etc/localtime:ro
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#       - ./static_new/:/GreaterWMS/static_new:ro
#     networks:
#       - basic
