# Generated by Django 3.1.14 on 2024-07-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='laneway',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Laneway'),
        ),
    ]
