# Generated by Django 3.1.14 on 2024-05-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='picking_task',
            field=models.SmallIntegerField(default=0, verbose_name='是否有拣货任务'),
        ),
    ]
