# Generated by Django 3.1.14 on 2023-11-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnlistmodel',
            name='comments',
            field=models.CharField(default='', max_length=255, verbose_name='备注'),
        ),
    ]
