# Generated by Django 3.1.14 on 2024-03-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn', '0002_dnlistmodel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='dndetailmodel',
            name='order_type',
            field=models.CharField(default='', max_length=255, verbose_name='Order Type'),
        ),
        migrations.AddField(
            model_name='dndetailmodel',
            name='txnid',
            field=models.CharField(default='', max_length=255, verbose_name='tp Code'),
        ),
        migrations.AddField(
            model_name='dnlistmodel',
            name='mian_dan',
            field=models.TextField(default='', verbose_name='Mian Dan'),
        ),
        migrations.AddField(
            model_name='dnlistmodel',
            name='order_type',
            field=models.CharField(default='', max_length=255, verbose_name='Order Type'),
        ),
        migrations.AddField(
            model_name='dnlistmodel',
            name='txnid',
            field=models.CharField(default='', max_length=255, verbose_name='tp Code'),
        ),
        migrations.AddField(
            model_name='pickinglistmodel',
            name='txnid',
            field=models.CharField(default='', max_length=255, verbose_name='tp Code'),
        ),
    ]
