# Generated by Django 3.1.14 on 2024-03-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn', '0003_auto_20240321_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnlistmodel',
            name='order_line',
            field=models.SmallIntegerField(default=1, verbose_name='Order Line'),
        ),
    ]
