# Generated by Django 3.1.14 on 2024-03-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn', '0004_dnlistmodel_order_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnlistmodel',
            name='tp_detail',
            field=models.JSONField(default=dict, verbose_name='tp detail'),
        ),
    ]
