# Generated by Django 3.1.14 on 2024-04-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn', '0005_dnlistmodel_tp_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnlistmodel',
            name='carrier',
            field=models.CharField(default='', max_length=255, verbose_name='Carrier'),
        ),
        migrations.AddField(
            model_name='dnlistmodel',
            name='have_mian_dan',
            field=models.BooleanField(default=False, verbose_name='Have Mian Dan'),
        ),
    ]
