# Generated by Django 3.1.14 on 2024-04-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn', '0006_auto_20240412_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickinglistmodel',
            name='picker',
            field=models.CharField(default='', max_length=255, verbose_name='Picker'),
        ),
    ]
