# Generated by Django 3.1.14 on 2024-04-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn', '0007_pickinglistmodel_picker'),
    ]

    operations = [
        migrations.AddField(
            model_name='dndetailmodel',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='dnlistmodel',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='优先级'),
        ),
    ]
