# Generated by Django 3.1.14 on 2024-04-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn', '0009_carrierlist_ordertypelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='dndetailmodel',
            name='carrier',
            field=models.CharField(default='', max_length=255, verbose_name='Carrier'),
        ),
        migrations.AddField(
            model_name='dndetailmodel',
            name='have_mian_dan',
            field=models.BooleanField(default=False, verbose_name='Have Mian Dan'),
        ),
        migrations.AddField(
            model_name='dndetailmodel',
            name='mian_dan',
            field=models.TextField(default='', verbose_name='Mian Dan'),
        ),
        migrations.AddField(
            model_name='dndetailmodel',
            name='order_line',
            field=models.SmallIntegerField(default=1, verbose_name='Order Line'),
        ),
        migrations.AddField(
            model_name='dndetailmodel',
            name='trackingnumber',
            field=models.CharField(default='', max_length=255, verbose_name='Tracking Number'),
        ),
        migrations.AddField(
            model_name='dnlistmodel',
            name='trackingnumber',
            field=models.CharField(default='', max_length=255, verbose_name='Tracking Number'),
        ),
        migrations.AddField(
            model_name='pickinglistmodel',
            name='bar_code',
            field=models.CharField(default='', max_length=255, verbose_name='Bar Code'),
        ),
    ]
